buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '3.0.197'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

version = "1.2-1.12.2"
group = "com.shadowking21.tc_integration"
archivesBaseName = "tc_integration"

def minecraftVersion = "1.12.2"
def forgeVersion = "14.23.5.2860"
def mappingChannel = "snapshot"
def mappingVersion = "20171003-1.12"

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: mappingChannel, version: mappingVersion

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                tc_integration {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                tc_integration {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url = 'https://cursemaven.com' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraftVersion}-${forgeVersion}"

    implementation fg.deobf('curse.maven:thaumcraft-223628:2629023')
    compileOnly fg.deobf('curse.maven:astral-sorcery-241721:3044416')
    compileOnly fg.deobf('curse.maven:baubles-227083:2518667')
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", minecraftVersion

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': minecraftVersion
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
